package frc.robot.visualization;

import edu.wpi.first.math.geometry.Translation3d;

/** Display-only CAD pivots. Generated by tools/robot-model/build_simcity_model.py. */
public final class RobotCadModelGeometry {
  private RobotCadModelGeometry() {}

  public static final Translation3d TURRET_PIVOT =
      new Translation3d(0.107948094606, -0.196847900748, 0.408560629531);
  public static final Translation3d HOOD_OFFSET =
      new Translation3d(0.089506447845, 0.000000000000, 0.053339987993);
  public static final double CAD_TURRET_YAW_RAD = -0.049179699417;
}
